### ISSUE TITLE
Prepare clips for labelling tracks

### ISSUE THREAD

**Issue by sfmig** [SainsburyWellcomeCentre/crabs-exploration#117]
From the available escape clips, which ones do we want to label?

Ideally spread across days and lightning conditions (we want variety).

**Comment by sannatitus** [comment]
Heya! I have just ffmpeg'd all escapes (234 total) and uploaded to the ceph (20% done now but will finish by 18:00 tonight, at \zoo\raw\CrabField\ramalhete_2023\Escapes\) . I'll also hand Sofia a hard copy this afternoon. This is every single triggered (researcher-provoked) escape and spontaneous escape (wind, tourists, where >4 crabs moved) that Nanci identified, from all research days. In general, more crabs escape within 'triggered' events however they became desensitised throughout the day, so it would be best to start with triggered escapes in the early study hours (videos 01, 02, 03 rather than 04+). We have significant light variation both within and across study days, so if we pick a small random subset we should be fine! Not sure how many me want to label exactly, but sliced videos range from 1-20 seconds. 

04.09.2023- is likely our most variable date; 04.09.2023-01-Right-Triggered1.mov is extremely rainy and dark. 04.09.2023-02-Right-Triggered1.mov was captured about an hour later, and it's far sunnier. 04.09.2023-05-Right-Triggered2.mov is the same day, but cloudy cover and unfocused. Focus changes spontaneously, even within the same video file unfortunately (tried to eliminate this as much as possible in the field, but it's still prevalent). I ffmpeg'd all escape videos from the right cameras for continuity, but I can absolutely do the left if anything is too unfocused to work with. Let me know if anyone wants all these videos also cut from the left camera and I can upload those to ceph too! 

Glancing quickly (so feel free to choose whatever you want!), my starting suggestions would be: 
09.08.2023-04-Right-Triggered2.mov
10.08.2023-02.Right-Triggered1.mov
10.08.2023-02.Right-Triggered2.mov
04.09.2023-01-Right-Triggered1.mov
04.09.2023-02-Right-Triggered1.mov
04.09.2023-05-Right-Triggered2.mov 
05.09.2023-01-Right-Triggered1.mov
05.09.2023-03-Right-Triggered4.mov - a wonderful long-distance escape, albeit a bit unfocused (let me know if you want left camera)
05.09.2023-04-Right.Triggered1.mov
05.09.2023-05-Right-Triggered1.mov - in this one, a crab is seen dragging seagrass as he escapes so may be a good example to check bounding box sensitivity haha
06.09.2023-02-Right-Triggered2.mov
06.09.2023-03-Right-Triggered2.mov
07.09.2023-01-Right-Triggered2.mov
